'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight} from 'lucide-react';
import {metaUrl,type Ad} from '@/lib/research';
import type {CreativeMedia} from '@/lib/media';
export function CreativePreview({ad,enabled,autoplay,onDetails}:{ad:Ad;enabled:boolean;autoplay:boolean;onDetails:()=>void}){
 const container=useRef<HTMLDivElement>(null);const video=useRef<HTMLVideoElement>(null);const [visible,setVisible]=useState(false);const [items,setItems]=useState<CreativeMedia[]>([]);const [index,setIndex]=useState(0);const [requested,setRequested]=useState(false);const [loading,setLoading]=useState(false);const [failed,setFailed]=useState(false);const [collectedAt,setCollectedAt]=useState<string|null>(null);
 useEffect(()=>{const node=container.current;if(!node)return;const observer=new IntersectionObserver(entries=>setVisible(entries[0].isIntersecting),{threshold:.35});observer.observe(node);return()=>observer.disconnect();},[]);
 useEffect(()=>{if(visible&&enabled)setRequested(true);},[visible,enabled,ad.image]);
 useEffect(()=>{if(!requested||!enabled )return;let active=true;setLoading(true);fetch(`/api/media?id=${ad.id}`).then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{if(active){setItems(data.items||[]);setCollectedAt(data.collectedAt||null);}}).catch(()=>{if(active)setFailed(true);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[requested,enabled,ad.id,ad.image]);
 useEffect(()=>{const v=video.current;if(!v)return;if(visible&&autoplay&&document.visibilityState==='visible'){v.muted=true;void v.play().catch(()=>{});}else v.pause();const change=()=>{if(document.hidden)v.pause();else if(visible&&autoplay){v.muted=true;void v.play().catch(()=>{});}};document.addEventListener('visibilitychange',change);return()=>document.removeEventListener('visibilitychange',change);},[visible,autoplay,index,items]);
 const item=items[index];return <div ref={container} className="media-container">{item&&!failed?<>{item.kind==='video'?<video ref={video} src={item.url} poster={item.poster} autoPlay={autoplay&&visible} muted loop playsInline controls preload="metadata" onError={()=>setFailed(true)} aria-label={`Ad video ${ad.id}`}/>:<img src={item.url} alt={`Ad creative for ${ad.pageName||'advertiser'}`} onError={()=>setFailed(true)}/>}<span className="media-caption">{item.kind==='video'?'Meta video · muted':'Meta ad image'}{collectedAt&&` · collected ${new Date(collectedAt).toLocaleDateString('en-GB')}`}</span>{items.length>1&&<div className="media-variants"><button onClick={()=>setIndex(i=>(i+items.length-1)%items.length)} aria-label="Previous creative variant">‹</button><span>{index+1}/{items.length}</span><button onClick={()=>setIndex(i=>(i+1)%items.length)} aria-label="Next creative variant">›</button></div>}</>:ad.image?<button className="creative-preview" onClick={onDetails}><img src={ad.image} alt="Sharps website reference, not actual ad"/><span className="image-label">Website reference image · sample</span></button>:<div className="copy-creative"><span className="eyebrow">{loading?'LOADING CREATIVE…':'THE MESSAGE'}</span><p>“{ad.copy.slice(0,210)}{ad.copy.length>210?'…':''}”</p><a href={metaUrl(ad.id)} target="_blank" rel="noreferrer">{failed?'Preview unavailable · view on Meta':'Creative not collected yet · view on Meta'}<ArrowUpRight size={16}/></a></div>}</div>;
}
