'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Image as ImageIcon} from 'lucide-react';
import {metaUrl,type Ad} from '@/lib/research';
import {safeMediaUrl,type CreativeMedia} from '@/lib/media';
import {creativeFormat,type CreativeFormat} from '@/lib/creative-mix';
export function CreativePreview({ad,enabled,autoplay,onDetails,onFormat}:{ad:Ad;enabled:boolean;autoplay:boolean;onDetails:()=>void;onFormat?:(id:string,format:CreativeFormat)=>void}){
 const container=useRef<HTMLDivElement>(null);const video=useRef<HTMLVideoElement>(null);const [visible,setVisible]=useState(false);const [nearby,setNearby]=useState(false);const [items,setItems]=useState<CreativeMedia[]>([]);const [index,setIndex]=useState(0);const [requested,setRequested]=useState(false);const [retry,setRetry]=useState(0);const [loading,setLoading]=useState(false);const [failed,setFailed]=useState(false);const [collectedAt,setCollectedAt]=useState<string|null>(null);
 useEffect(()=>{const node=container.current;if(!node)return;const observer=new IntersectionObserver(entries=>setVisible(entries[0].isIntersecting),{threshold:.35});const preload=new IntersectionObserver(entries=>setNearby(entries[0].isIntersecting),{threshold:.01,rootMargin:'250px 0px'});observer.observe(node);preload.observe(node);return()=>{observer.disconnect();preload.disconnect();};},[]);
 useEffect(()=>{if(nearby&&enabled)setRequested(true);},[nearby,enabled]);
 useEffect(()=>{if(!requested||!enabled)return;const controller=new AbortController();let active=true;setLoading(true);setFailed(false);setIndex(0);
 const wait=(ms:number)=>new Promise<void>(resolve=>{const timer=setTimeout(resolve,ms);controller.signal.addEventListener('abort',()=>{clearTimeout(timer);resolve();},{once:true});});
 (async()=>{try{let data:any;for(let attempt=0;attempt<3;attempt++){if(controller.signal.aborted)return;const r=await fetch(`/api/media?id=${ad.id}${retry?'&refresh=1':''}`,{signal:controller.signal});data=await r.json();if(!['BUSY','COLLECTOR_UNAVAILABLE'].includes(data.code)||attempt===2)break;await wait((attempt+1)*4000);}
 if(active){const media:CreativeMedia[]=(Array.isArray(data?.items)?data.items:[]).flatMap((item:any)=>{const url=safeMediaUrl(item?.url);return url&&['image','video'].includes(item?.kind)?[{kind:item.kind,url,poster:safeMediaUrl(item.poster)||undefined}]:[];});setItems(media);setCollectedAt(data?.collectedAt||null);setFailed(!media.length);}}
 catch{if(active)setFailed(true);}finally{if(active)setLoading(false);}})();return()=>{active=false;controller.abort();};
 },[requested,enabled,ad.id,retry]);
 useEffect(()=>{if(items.length)onFormat?.(ad.id,creativeFormat(items));},[items,ad.id,onFormat]);
 useEffect(()=>{const v=video.current;if(!v)return;if(visible&&autoplay&&document.visibilityState==='visible'){v.muted=true;void v.play().catch(()=>{});}else v.pause();const change=()=>{if(document.hidden)v.pause();else if(visible&&autoplay){v.muted=true;void v.play().catch(()=>{});}};document.addEventListener('visibilitychange',change);return()=>document.removeEventListener('visibilitychange',change);},[visible,autoplay,index,items]);
 const failedMedia=()=>{setFailed(true);if(retry===0)setRetry(1);};const item=items[index];
 return <div ref={container} className="media-container">{item&&!failed?<>{item.kind==='video'?<video ref={video} src={item.url} poster={item.poster} autoPlay={autoplay&&visible} muted loop playsInline controls preload="metadata" onError={failedMedia} aria-label={`Ad video ${ad.id}`}/>:<img src={item.url} alt={`Ad creative for ${ad.pageName||'advertiser'}`} onError={failedMedia}/>}<span className="media-caption">{item.kind==='video'?'Video creative · muted':'Static creative'}{collectedAt&&` · checked ${new Date(collectedAt).toLocaleDateString('en-GB')}`}</span>{items.length>1&&<div className="media-variants"><button onClick={()=>setIndex(i=>(i+items.length-1)%items.length)} aria-label="Previous creative variant">‹</button><span>{index+1}/{items.length}</span><button onClick={()=>setIndex(i=>(i+1)%items.length)} aria-label="Next creative variant">›</button></div>}</>:ad.image?<button className="creative-preview" onClick={onDetails}><img src={ad.image} alt="Sharps website reference, not actual ad"/><span className="image-label">Website reference image · sample</span></button>:<div className={'creative-placeholder '+(loading?'is-loading':'')} aria-busy={loading}><div className="creative-placeholder-icon"><ImageIcon size={30}/></div><span className="eyebrow">{loading?'LOADING THE CREATIVE':'CREATIVE PREVIEW'}</span><strong>{loading?'Finding the image or video…':'Preview unavailable'}</strong><small>{loading?'First previews can take longer while the collector wakes up.':'The ad copy and reported metrics remain below.'}</small>{!loading&&<><a href={metaUrl(ad.id)} target="_blank" rel="noreferrer">View creative on Meta<ArrowUpRight size={15}/></a><button className="text-button" onClick={()=>setRetry(v=>v+1)}>Retry preview</button></>}</div>}</div>;
}
