'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowUpRight,Download,Network,Sparkles} from 'lucide-react';
import {messageCategories,messagingThemes,themeExamples,messagingExport,type MessageCategory} from '@/lib/messaging';
import {number,pattern,type Ad} from '@/lib/research';
export function MessagingMap({ads,brand,pageId,at,onAd}:{ads:Ad[];brand:string;pageId:string;at:string;onAd:(ad:Ad)=>void}){
 const themes=useMemo(()=>messagingThemes(ads),[ads]);const [selected,setSelected]=useState('');const [expanded,setExpanded]=useState<MessageCategory|null>(null);const [notes,setNotes]=useState<Record<string,string>>({});const [ready,setReady]=useState(false);const [storageError,setStorageError]=useState(false);
 const storageKey=`messaging-map-notes-v1:${pageId||brand}`;
 useEffect(()=>{try{const value=JSON.parse(localStorage.getItem(storageKey)||'{}');setNotes(value&&typeof value==='object'&&!Array.isArray(value)?Object.fromEntries(Object.entries(value).filter(([,v])=>typeof v==='string')) as Record<string,string>:{});}catch{setStorageError(true);}setReady(true);},[storageKey]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(storageKey,JSON.stringify(notes));}catch{setStorageError(true);}},[notes,ready,storageKey]);
 const theme=themes.find(t=>t.id===selected);const examples=theme?themeExamples(theme,at):[];const copyCount=new Set(ads.map(pattern)).size;const unmapped=ads.filter(a=>!themes.some(t=>t.ads.some(b=>b.id===a.id))).length;
 const exportMap=()=>{const url=URL.createObjectURL(new Blob([messagingExport(brand,themes,at,notes)],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='messaging-map.txt';link.click();URL.revokeObjectURL(url);};
 const branch=(category:MessageCategory)=>{const info=messageCategories.find(c=>c.id===category)!;const list=themes.filter(t=>t.category===category);return <section className={`message-branch branch-${category}`} aria-label={info.label}><div className="branch-heading"><span className="branch-dot"/><h3>{info.label}</h3><span>{list.length}</span></div><p>{info.question}</p><div className="theme-chips">{(expanded===category?list:list.slice(0,3)).map(t=><button key={t.id} aria-pressed={selected===t.id} onClick={()=>setSelected(t.id)}><span>{t.label}</span><strong>{t.ads.length}</strong></button>)}{!list.length&&<span className="branch-empty">No theme detected in the loaded copy</span>}</div>{list.length>3&&<button className="branch-more" onClick={()=>setExpanded(expanded===category?null:category)}>{expanded===category?'Show less':`+ ${list.length-3} more themes`}</button>}</section>;};
 return <section className="messaging-workspace" aria-label="Messaging map"><div className="message-map-header"><div><span className="eyebrow">FROM AD COPY TO CREATIVE DIRECTION</span><h2>Map the message. Find your angle.</h2><p>{ads.length} ads · {copyCount} distinct copy patterns · Click a theme to inspect its evidence.</p></div><button className="outline-button" onClick={exportMap} disabled={!ads.length}><Download size={15}/>Export map</button></div><div className="message-map-canvas"><svg className="map-connections" viewBox="0 0 1000 500" preserveAspectRatio="none" aria-hidden="true"><path d="M500 205 C370 205 370 110 260 110 M500 205 C370 205 370 350 260 350 M500 205 C630 205 630 110 740 110 M500 205 C630 205 630 350 740 350 M500 205 L500 410"/></svg><div className="map-column">{branch('hooks')}{branch('benefits')}</div><div className="map-column map-center"><div className="message-brand-node"><div className="map-brand-icon"><Network size={27}/></div><span className="eyebrow">THE ADVERTISER</span><h3>{brand}</h3><p>{themes.length} messaging themes</p><span>Detected from ad text</span></div>{branch('actions')}</div><div className="map-column">{branch('offers')}{branch('proof')}</div></div><p className="message-map-caveat">Copy-based observations · Ads can appear in multiple themes. Claims in ad copy are not independently verified. {unmapped>0&&`${unmapped} ads had no recognised theme. `}Images and videos have not been analysed.</p>
 {theme?<div className="message-evidence" aria-live="polite"><div className="message-evidence-header"><div><span className="eyebrow">{messageCategories.find(c=>c.id===theme.category)?.label} → {theme.label}</span><h3>{examples.length} distinct messages across {theme.ads.length} ads</h3><p>Examples are ordered by reported UK reach. Grouped by full ad copy; excerpts may repeat.</p></div><button className="text-button" onClick={()=>setSelected('')}>Clear selection</button></div><div className="message-evidence-grid"><div className="message-quotes">{examples.map(ad=><button key={ad.id} className="message-quote" onClick={()=>onAd(ad)}><span>“{theme.evidence[ad.id]}”</span><small><span>UK reach {number(ad.reach)}</span><span>Open ad & brief <ArrowUpRight size={13}/></span></small></button>)}</div><aside className="message-test"><div className="eyebrow"><Sparkles size={14}/>YOUR NEXT EXPERIMENT</div><h3>Adapt the principle to your brand</h3><p>{theme.test}</p><label>Your test direction<textarea aria-label="Messaging test direction" placeholder="Your audience, original hook, evidence and one variable to test…" value={notes[theme.id]||''} onChange={e=>setNotes(old=>({...old,[theme.id]:e.target.value}))} maxLength={5000}/></label><small>{storageError?'Notes could not be saved on this device. Export the map to keep them.':'Notes saved on this device · Included in map export'}</small></aside></div></div>:<div className="message-map-prompt"><Network size={20}/><div><strong>Follow a branch to the actual ads.</strong><p>Select a theme above to see the words behind it and shape your own test direction.</p></div></div>}
 </section>;
}
