"use client";
import {useEffect,useMemo,useState,useRef} from "react";
import {Search,SlidersHorizontal,Bookmark,ExternalLink,Link2,LayoutGrid,X,Play,CalendarDays,Sparkles,Check,Globe,Layers,ArrowDownWideNarrow} from "lucide-react";
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from "@/components/ui/sheet";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Checkbox} from "@/components/ui/checkbox";
type Ad={id:string;title:string;copy:string;start:string;format:"Video"|"Image"|"Unknown";duration?:string;angle:string;image:string;source:string;analysis:string;pageId?:string;pageName?:string;stop?:string|null;platforms?:string[];reach?:number|null;locations?:{name:string;excluded:boolean}[];ages?:string[];funnel?:string};
const images=["https://cdn.sharps.co.uk/media/assets/studio-collection-phase-two/studio-duskypink-sorrento-560x700.jpg","https://cdn.sharps.co.uk/media/assets/homepage/banner/which_room_living-25.jpg","https://cdn.sharps.co.uk/media/assets/homepage/banner/which_room_office.jpg"];
const sale="Half Price Sale Now On. Plus an extra 20% off. Transform your space with the UK's No.1 fitted furniture company, backed by an industry-leading 15-year guarantee. Book your free design visit with Sharps today.";
const ads:Ad[]=[
{id:"1439262321695837",platforms:["facebook","instagram","messenger","threads"],reach:47,ages:["25","65"],funnel:"TOFU",title:"It's what's inside that counts",copy:"Explore fitted furniture that's designed around you, and the things you love.",start:"2026-10-07",format:"Video",duration:"0:06",angle:"Lifestyle",image:images[0],source:"Meta API",analysis:"The headline shifts attention from furniture to the things a customer values. A lifestyle-led awareness angle. This is an editorial interpretation of the copy, not a Meta performance metric."},
{id:"1675773394116893",title:"Fitted furniture for every room",copy:"Open this ad in Meta to inspect its creative variants. Body text was not exposed in the captured preview.",start:"2026-09-30",format:"Video",duration:"1:00",angle:"Brand",image:images[1],source:"Meta Ad Library",analysis:"The longer video format can accommodate a broader brand story. Its hook and visual sequence still need review; duration alone does not tell us how well it performs."},
{id:"1371182101209589",title:"Book your free design visit today",copy:"Half Price Sale Now On. Plus an extra 20% off. Transform your space with the UK's No.1 fitted furniture company and Which? Recommended Provider for Fitted Bedrooms. Book your free design visit with Sharps today.",start:"2026-08-21",format:"Image",angle:"Offer",image:images[2],source:"Meta Ad Library",analysis:"The offer stacks two price incentives and uses independent endorsement as reassurance. A free design visit lowers the next-step commitment. An offer-led conversion angle; actual conversion results are unavailable."},
{id:"2628255447612072",title:"One home. Endless possibilities",copy:"Explore our Studio Collection and showcase your own unique expression with a curated selection of colours, styles and frames.",start:"2026-08-12",format:"Image",angle:"Product",image:images[0],source:"Meta Ad Library",analysis:"Personal expression and variety are the core benefits. A product-led consideration angle, with a specific collection for interested customers to explore."},
{id:"1744405716612975",title:"Book your free design visit today",copy:sale,start:"2026-08-21",format:"Video",duration:"0:10",angle:"Offer",image:images[1],source:"Meta Ad Library",analysis:"This short video pairs a sale with a long guarantee. The guarantee addresses durability concerns, while a free appointment reduces friction. These are messaging observations, not measured outcomes."},
{id:"1117562100730661",title:"Built to last, designed to renew",copy:"Keep what matters and refresh what you see with Sharps Renew for Sharps Signature wardrobes. Perfect storage with style that changes with you.",start:"2026-09-24",format:"Video",duration:"0:39",angle:"Product",image:images[2],source:"Meta Ad Library",analysis:"The copy reframes furniture as adaptable over time. It pairs longevity with changing style, giving this creative a distinct angle from the price-led sale ads."}];
const metaUrl=(id:string)=>`https://www.facebook.com/ads/library/?id=${id}`;
function normalize(input:string){const text=input.trim();if(/^(https?:\/\/|www\.)/i.test(text)||/^[\w-]+\.[a-z]{2,}(\/.*)?$/i.test(text)){try{return new URL(/^https?:\/\//i.test(text)?text:`https://${text}`).hostname.replace(/^www\./,"");}catch{}}return text;}
const date=(value:string)=>new Date(value+"T12:00:00Z").toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric",timeZone:"Europe/London"});
const days=(value:string,end="2026-10-08")=>Math.max(1,Math.floor((Date.parse(end+"T12:00:00Z")-Date.parse(value+"T12:00:00Z"))/86400000));
export default function Home(){
 const requestId=useRef(0);const [live,setLive]=useState<Ad[]|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [discovery,setDiscovery]=useState(false);const [captured,setCaptured]=useState("");const [cursor,setCursor]=useState<string|null>(null);const [pageId,setPageId]=useState("");const [query,setQuery]=useState("");const [submitted,setSubmitted]=useState("sharps");const [tab,setTab]=useState("research");const [saved,setSaved]=useState<string[]>([]);const [followed,setFollowed]=useState(false);const [followedOnly,setFollowedOnly]=useState(false);const [filters,setFilters]=useState(false);const [format,setFormat]=useState("all");const [angle,setAngle]=useState("all");const [period,setPeriod]=useState("all");const [sort,setSort]=useState("newest");const [selected,setSelected]=useState<Ad|null>(null);const [term,setTerm]=useState("");const [ready,setReady]=useState(false);
 useEffect(()=>{try{const stored=JSON.parse(localStorage.getItem("ad-library-saved")||"[]");setSaved(Array.isArray(stored)?stored.filter(x=>typeof x==="string"):[]);setFollowed(localStorage.getItem("ad-library-followed")==="true");}catch{}setReady(true);},[]);
 useEffect(()=>{if(ready){try{localStorage.setItem("ad-library-saved",JSON.stringify(saved));localStorage.setItem("ad-library-followed",String(followed));}catch{}}},[saved,followed,ready]);
 const load=async(value:string,page="",after="")=>{const request=++requestId.current;setLoading(true);setError("");try{const params=new URLSearchParams({q:value});if(page)params.set("page",page);if(after)params.set("after",after);const response=await fetch(`/api/ads?${params}`);const data=await response.json();if(request!==requestId.current)return;if(!response.ok)throw new Error(data.error||"Search failed.");setLive(previous=>after?[...(previous||[]),...data.ads.filter((a:Ad)=>!previous?.some(p=>p.id===a.id))]:data.ads);setDiscovery(data.discovery);setCaptured(data.capturedAt);setCursor(data.nextCursor);setPageId(data.pageId||"");}catch(e){if(request!==requestId.current)return;setError(e instanceof Error?e.message:"Search failed.");if(!after)setLive(null);}finally{if(request===requestId.current)setLoading(false);}};
 const search=(value:string)=>{if(!value.trim())return;setSubmitted(normalize(value));setSelected(null);setTerm("");setTab("research");setLive(null);void load(value);};
 const sample=()=>{requestId.current++;setLoading(false);setSubmitted("sharps");setLive(null);setError("");setTerm("");};
 const running=(ad:Ad)=>ad.start?days(ad.start,live?(ad.stop||captured.slice(0,10)):undefined):0;
 const country=(ad:Ad)=>ad.locations?.filter(l=>!l.excluded).map(l=>l.name).join(", ")||"Not provided";
 const platforms=(ad:Ad)=>ad.platforms?.join(", ")||"Not captured";
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();try{Promise.resolve(context.registerTool({name:"search_brand",title:"Search brand or URL",description:"Search Meta ads for a brand or URL; matching advertisers can be selected.",inputSchema:{type:"object",properties:{query:{type:"string",minLength:1,maxLength:200}},required:["query"],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:any){if(typeof input?.query!=="string"||!input.query.trim()||input.query.length>200)throw new Error("Enter a brand or URL of 1–200 characters.");search(input.query);return {query:normalize(input.query),source:"Meta search requested"};}},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();},[]);
 const isSharps=/^(sharps|sharps fitted furniture|sharps\.co\.uk)$/i.test(submitted)||submitted==="";
 const visible=useMemo(()=>(live||ads).filter(a=>(tab!=="saved"||saved.includes(a.id))&&(!followedOnly||followed)&&(format==="all"||a.format===format)&&(angle==="all"||a.angle===angle)&&(period==="all"||running(a)<=Number(period))&&(!term||`${a.title} ${a.copy}`.toLowerCase().includes(term.toLowerCase()))).sort((a,b)=>sort==="oldest"?a.start.localeCompare(b.start):b.start.localeCompare(a.start)),[live,captured,tab,saved,followedOnly,followed,format,angle,period,sort,term]);
 const toggleSave=(id:string)=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);const reset=()=>{setFormat("all");setAngle("all");setPeriod("all");setFollowedOnly(false);setTerm("");};const filterCount=Number(format!=="all")+Number(angle!=="all")+Number(period!=="all")+Number(followedOnly);
 return <main><header className="app-header"><a className="wordmark" href="/" aria-label="AD Library Scraper home"><span className="logo"><Layers size={21}/></span>ad<span className="wordmark-light">library</span><span className="wordmark-caption">SCRAPER</span></a><span className="header-divider"/><span className="workspace-name">Creative research</span><div className="header-right"><span className="preview-label">Creative research</span><span className="avatar">RW</span></div></header>
 <section className="workspace"><div className="title-row"><div><div className="eyebrow">YOUR RESEARCH WORKSPACE</div><h1>Find your next creative angle.</h1></div><a className="outline-button" href="https://www.facebook.com/ads/library/" target="_blank" rel="noreferrer"><ExternalLink size={16}/>Meta Ad Library</a></div>
 <form className="brand-search" onSubmit={e=>{e.preventDefault();search(query);}}><Search size={23}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a brand or paste a website URL…" aria-label="Brand name or website URL" maxLength={200}/><span className="search-hint"><Link2 size={15}/>Brand or URL</span><button className="primary-button" type="submit" disabled={loading}>{loading?"Searching…":"Search ads"}</button></form>
 <div className="sample-notice"><span className="notice-dot"/>{live?`Meta API · Retrieved ${new Date(captured).toLocaleString("en-GB")}`:"Verified sample · 8 Oct 2026"}<span className="notice-separator">/</span><span>{live?"UK active ads · Reach is reported by location":"Search to request live ads."}</span><button className="text-button" onClick={sample}>Explore sample</button></div>{error&&<p role="alert" className="sample-notice">{error}</p>}
 {live&&discovery&&<section className="sample-notice"><strong>Select the matching advertiser:</strong>{Array.from(new Map(live.map(a=>[a.pageId,a])).values()).map(a=><button className="outline-button" key={a.pageId} onClick={()=>load(submitted,a.pageId)}>{a.pageName} · {a.pageId}</button>)}<span>Keyword results can include unrelated businesses. A URL supplies search terms; it does not verify ownership.</span></section>}
 {(isSharps||live)?<><div className="brand-row"><span className="brand-logo">{live?"ads":"sharps"}</span><div className="brand-identity"><h2>{live?(discovery?"Advertiser discovery":live[0]?.pageName||submitted):"Sharps Fitted Furniture"} <Check size={16}/></h2>{!live&&<a href="https://www.sharps.co.uk/" target="_blank" rel="noreferrer">sharps.co.uk <ExternalLink size={12}/></a>}</div><div className="brand-meta"><span><Globe size={15}/>United Kingdom</span><span>Page {live?(pageId||"Choose advertiser"):"280531915302272"}</span></div>{!live&&<button className={"outline-button follow-button "+(followed?"is-followed":"")} onClick={()=>setFollowed(x=>!x)}>{followed?<Check size={16}/>:<Bookmark size={16}/>} {followed?"Following":"Follow brand"}</button>}</div>
 <div className="research-toolbar"><Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="research-tabs"><TabsTrigger value="research"><LayoutGrid size={16}/>Research <span className="count">{(live||ads).length}</span></TabsTrigger><TabsTrigger value="saved"><Bookmark size={16}/>Saved <span className="count">{saved.length}</span></TabsTrigger></TabsList></Tabs><div className="toolbar-right"><button className="outline-button" onClick={()=>setFilters(!filters)} aria-expanded={filters}><SlidersHorizontal size={16}/>Filters {filterCount>0&&<span className="filter-count">{filterCount}</span>}</button><Select value={period} onValueChange={setPeriod}><SelectTrigger aria-label="Date range" className="toolbar-select"><CalendarDays size={16}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All start dates</SelectItem><SelectItem value="7">Last 7 days</SelectItem><SelectItem value="30">Last 30 days</SelectItem><SelectItem value="90">Last 90 days</SelectItem></SelectContent></Select><Select value={sort} onValueChange={setSort}><SelectTrigger aria-label="Sort ads" className="toolbar-select"><ArrowDownWideNarrow size={16}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="newest">Newest first</SelectItem><SelectItem value="oldest">Oldest first</SelectItem></SelectContent></Select></div></div>
 {filters&&<div className="filter-panel"><div><span>Creative format</span><Select value={format} onValueChange={setFormat}><SelectTrigger aria-label="Creative format"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All formats</SelectItem><SelectItem value="Video">Video</SelectItem><SelectItem value="Image">Image</SelectItem></SelectContent></Select></div><div><span>Messaging angle</span><Select value={angle} onValueChange={setAngle}><SelectTrigger aria-label="Messaging angle"><SelectValue/></SelectTrigger><SelectContent>{["all","Lifestyle","Offer","Product","Brand"].map(v=><SelectItem key={v} value={v}>{v==="all"?"All angles":v}</SelectItem>)}</SelectContent></Select></div><label><Checkbox checked={followedOnly} onCheckedChange={v=>setFollowedOnly(v===true)}/>Followed brands only</label><button className="text-button" onClick={reset}>Reset filters</button></div>}
 <div className="result-row"><p><strong>{visible.length} creatives</strong> {live?"returned":"in this sample"} <span>· Active when captured</span></p><div className="within-search"><Search size={15}/><input aria-label="Search within ads" placeholder="Search ad copy…" value={term} onChange={e=>setTerm(e.target.value)}/>{term&&<button aria-label="Clear ad copy search" onClick={()=>setTerm("")}><X size={14}/></button>}</div></div>
 <div className="creative-grid">{visible.map(ad=><article className="ad-card" key={ad.id}><div className="card-header"><span className="mini-brand">s</span><strong>{ad.pageName||"Sharps Fitted Furniture"}</strong><button className={"save-button "+(saved.includes(ad.id)?"saved":"")} aria-label={(saved.includes(ad.id)?"Unsave ":"Save ")+ad.title} onClick={()=>toggleSave(ad.id)}><Bookmark size={19} fill={saved.includes(ad.id)?"currentColor":"none"}/></button></div><button className="creative-preview" onClick={()=>setSelected(ad)} aria-label={"View details: "+ad.title}>{ad.image?<img src={ad.image} alt="Sharps fitted furniture website reference" loading="lazy"/>:<span style={{display:"grid",placeItems:"center",minHeight:240}}>Open Meta to view this creative <ExternalLink size={24}/></span>}<span className="format-badge">{ad.format==="Video"?<Play size={12}/>:<Layers size={12}/>} {ad.duration||ad.format}</span><span className="image-label">{live?"Creative available on Meta":"Website reference image"}</span>{ad.format==="Video"&&<span className="play-circle"><Play size={22} fill="currentColor"/></span>}</button><div className="card-body"><div className="card-tags"><span className="status">Active at capture</span><span className="angle-tag">{ad.angle}</span></div><h3>{ad.title}</h3><p className="ad-copy">{ad.copy}</p><dl><div><dt>Start date</dt><dd>{ad.start?date(ad.start):"Not provided"}</dd></div><div><dt>Running at capture</dt><dd>{running(ad)} {running(ad)===1?"day":"days"}</dd></div><div><dt>Platforms</dt><dd>{platforms(ad)}</dd></div><div><dt>UK reach</dt><dd>{ad.reach==null?"Not captured":ad.reach.toLocaleString()}</dd></div><div><dt>Country</dt><dd>{live?country(ad):"United Kingdom"}</dd></div><div><dt>Funnel stage · estimated</dt><dd>{ad.funnel||(ad.angle==="Offer"?"BOFU":ad.angle==="Product"?"MOFU":"TOFU")}</dd></div></dl></div><div className="card-footer"><button onClick={()=>setSelected(ad)}>View details</button><a href={metaUrl(ad.id)} target="_blank" rel="noreferrer">View creative <ExternalLink size={14}/></a></div></article>)}</div>
 {visible.length===0&&<div className="empty-state"><Bookmark size={28}/><h3>{tab==="saved"?"Your saved collection starts here":"No creatives match these filters"}</h3><p>{tab==="saved"?"Save a creative from Research to keep it on this device.":"Try another date range, format or messaging angle."}</p><button className="outline-button" onClick={()=>{reset();setTab("research");}}>Show all sample ads</button></div>}
 <div className="end-note">{live?`${live.length} ads loaded. Meta may return only ads covered by the API.`:"Showing 6 captured examples, not Sharps’ complete ad library."}{live&&cursor&&<button className="outline-button" disabled={loading} onClick={()=>load(submitted,pageId,cursor)}>Load more ads</button>} {!discovery&&<a href={`https://www.facebook.com/ads/library/?active_status=active&ad_type=all&country=GB&view_all_page_id=${live?pageId:"280531915302272"}`} target="_blank" rel="noreferrer">Browse advertiser on Meta <ExternalLink size={12}/></a>}</div></>:<section className="discovery-state"><span className="discovery-icon"><Search size={30}/></span><div className="eyebrow">BRAND DISCOVERY</div><h2>Research “{submitted}”</h2><p>Your search is ready. Use Search ads to request matching advertisers from Meta. Find the matching advertiser on Meta to view its current creatives.</p><a className="primary-button" href={`https://www.facebook.com/ads/library/?active_status=active&ad_type=all&country=GB&q=${encodeURIComponent(submitted.replace(/\.(co\.uk|com|org|net)$/i,""))}&search_type=keyword_unordered`} target="_blank" rel="noreferrer">Find advertiser on Meta <ExternalLink size={16}/></a><button className="text-button" onClick={()=>{setQuery("");sample();}}>Return to the verified Sharps sample</button></section>}
 </section><Sheet open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><SheetContent className="detail-panel sm:max-w-[560px] w-full overflow-y-auto"><SheetHeader><div className="eyebrow">CREATIVE DETAILS</div><SheetTitle>{selected?.title}</SheetTitle><SheetDescription>{selected?.pageName||"Sharps Fitted Furniture"} · {live?"Meta API":"Verified sample"}</SheetDescription></SheetHeader>{selected&&<div className="detail-body">{selected.image&&<img src={selected.image} alt="Sharps website reference imagery"/>}<p className="detail-caption">{live?"Open Meta to view the actual creative.":"Website reference image. Open Meta to see the actual ad creative."}</p><a className="primary-button detail-link" href={metaUrl(selected.id)} target="_blank" rel="noreferrer">View actual creative on Meta <ExternalLink size={17}/></a><h3>Ad copy</h3><p>{selected.copy}</p><div className="analysis-box"><h3><Sparkles size={17}/>Messaging analysis <span>Editorial</span></h3><p>{selected.analysis}</p></div><dl><div><dt>Ad Library ID</dt><dd>{selected.id}</dd></div><div><dt>Format</dt><dd>{selected.format}{selected.duration&&` · ${selected.duration}`}</dd></div><div><dt>Started</dt><dd>{selected.start?date(selected.start):"Not provided"}</dd></div><div><dt>UK reach</dt><dd>{selected.reach==null?"Not captured":selected.reach.toLocaleString()}</dd></div><div><dt>Target age range</dt><dd>{selected.ages?.join("–")||"Not captured"}</dd></div><div><dt>Captured</dt><dd>{live?new Date(captured).toLocaleString("en-GB"):"8 October 2026"}</dd></div></dl><button className="outline-button" onClick={()=>toggleSave(selected.id)}><Bookmark size={16}/>{saved.includes(selected.id)?"Remove from saved":"Save creative"}</button></div>}</SheetContent></Sheet><footer className="app-footer"><span>AD Library Scraper</span><span>{live?"Live Meta results":"Verified sample"}</span><span>Saved items stay on this device</span></footer></main>;
}
