"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Search,Bookmark,ExternalLink,Layers,Download,GitCompareArrows,X,ArrowUpRight,Sparkles,SlidersHorizontal,RefreshCw,Check} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {CreativeMark,CreativeMoodboard} from '@/components/research/creative-art';
import {MessagingMap} from '@/components/research/messaging-map';
import {CreativePreview} from '@/components/research/creative-preview';
import {CreativeMix} from '@/components/research/creative-mix';
import type {CreativeFormat} from '@/lib/creative-mix';
import {advertiserScore,matchingAdvertisers,librarySearchUrl} from '@/lib/brand-search';
import {fetchResearch,validSnapshot,validRecoveryRequest,needsLogin,type ResearchSnapshot,type RecoveryRequest} from '@/lib/recovery';
import {sampleAds} from '@/lib/sample';
import {type Ad,metaUrl,elapsed,number,impressionLabel,impressionLower,stage,pattern,sortAds,csv,brief} from '@/lib/research';
const capturedSample='2026-10-08T12:00:00Z';
type Recent={query:string;page:string;name:string};
const download=(name:string,text:string,type='text/plain')=>{const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);};
function BrandLogo({id,name}:{id:string;name:string}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[id]);return <span className="advertiser-logo">{!failed&&/^\d+$/.test(id)?<img src={`https://graph.facebook.com/v26.0/${id}/picture?type=large`} alt={`${name} logo`} onError={()=>setFailed(true)}/>:<span aria-label={`${name} logo unavailable`}>{name.split(/\s+/).map(s=>s[0]).slice(0,2).join('').toUpperCase()}</span>}</span>;}
export default function Home(){
 const [coverage,setCoverage]=useState('GB');const [query,setQuery]=useState('');const [submitted,setSubmitted]=useState('Sharps');const [rows,setRows]=useState<Ad[]>(sampleAds);const [live,setLive]=useState(false);const [at,setAt]=useState(capturedSample);const [page,setPage]=useState('280531915302272');const [discovery,setDiscovery]=useState(false);const [cursor,setCursor]=useState<string|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const request=useRef(0);const editing=useRef(false);const searchTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const activeSearch=useRef<AbortController|null>(null);
 const [errorCode,setErrorCode]=useState('');const [pendingResearch,setPendingResearch]=useState<RecoveryRequest|null>(null);const [lastResearch,setLastResearch]=useState<ResearchSnapshot|null>(null);const resumed=useRef(false);const [mediaEnabled,setMediaEnabled]=useState(false);const [autoplay,setAutoplay]=useState(true);
 useEffect(()=>{fetch('/api/health').then(r=>r.json()).then(data=>{setMediaEnabled(data.mediaConfigured===true);}).catch(()=>{});try{setAutoplay(localStorage.getItem('ad-autoplay')!=='false');}catch{}},[]);
 const [view,setView]=useState<'ads'|'map'>('ads');const [sort,setSort]=useState('reach');const [tab,setTab]=useState('research');const [platform,setPlatform]=useState('all');const [funnel,setFunnel]=useState('all');const [period,setPeriod]=useState('all');const [minReach,setMinReach]=useState('');const [term,setTerm]=useState('');const [group,setGroup]=useState(false);const [filters,setFilters]=useState(false);const [saved,setSaved]=useState<Ad[]>([]);const [notes,setNotes]=useState<Record<string,string>>({});const [recent,setRecent]=useState<Recent[]>([]);const [ready,setReady]=useState(false);const [selected,setSelected]=useState<Ad|null>(null);const [compare,setCompare]=useState<Ad[]>([]);const [comparing,setComparing]=useState(false);const [storageMessage,setStorageMessage]=useState('');
 function restoreSnapshot(snapshot:ResearchSnapshot){setCoverage(snapshot.coverage==='EU_UK'?'EU_UK':'GB');setQuery(snapshot.query||'');setSubmitted(snapshot.submitted||'');setRows(snapshot.rows);setLive(snapshot.live===true);setAt(snapshot.at);setPage(snapshot.page||'');setDiscovery(snapshot.discovery===true);setCursor(snapshot.cursor||null);setView(snapshot.view==='map'?'map':'ads');setSort(snapshot.sort||'reach');setTab(snapshot.tab||'research');setPlatform(snapshot.platform||'all');setFunnel(snapshot.funnel||'all');setPeriod(snapshot.period||'all');setMinReach(snapshot.minReach||'');setTerm(snapshot.term||'');setGroup(snapshot.group===true);setSelected(snapshot.rows.find((a:Ad)=>a.id===snapshot.selectedId)||null);}
 useEffect(()=>{try{const session=JSON.parse(sessionStorage.getItem('ad-research-session-v1')||'null');if(validSnapshot(session))restoreSnapshot(session);const previous=JSON.parse(sessionStorage.getItem('ad-research-last-success-v1')||'null');if(validSnapshot(previous)&&previous.rows.length)setLastResearch(previous);const pending=JSON.parse(sessionStorage.getItem('ad-research-retry-v1')||'null');if(validRecoveryRequest(pending))setPendingResearch(pending);const s=JSON.parse(localStorage.getItem('research-board-v2')||'[]');const n=JSON.parse(localStorage.getItem('research-notes-v2')||'{}');const r=JSON.parse(localStorage.getItem('research-recent-v2')||'[]');setSaved(localStorage.getItem('research-board-v2')&&Array.isArray(s)?s.filter(a=>a&&typeof a.id==='string'&&typeof a.copy==='string'):sampleAds.filter(a=>{const legacy=JSON.parse(localStorage.getItem('ad-library-saved')||'[]');return Array.isArray(legacy)&&legacy.includes(a.id);}));setNotes(n&&typeof n==='object'&&!Array.isArray(n)?n:{});setRecent(Array.isArray(r)?r.filter(a=>a&&typeof a.query==='string'&&typeof a.page==='string'&&/^\d{1,30}$/.test(a.page)&&typeof a.name==='string'):[]);}catch{setStorageMessage('Browser storage is unavailable. Export your research to keep it.');}setReady(true);},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem('research-board-v2',JSON.stringify(saved));localStorage.setItem('research-notes-v2',JSON.stringify(notes));localStorage.setItem('research-recent-v2',JSON.stringify(recent));}catch{setStorageMessage('Could not save on this device. Export your research to keep it.');}},[saved,notes,recent,ready]);
 useEffect(()=>{if(!ready||loading)return;try{const snapshot={view,coverage,query,submitted,rows,live,at,page,discovery,cursor,sort,tab,platform,funnel,period,minReach,term,group,selectedId:selected?.id||null};sessionStorage.setItem('ad-research-session-v1',JSON.stringify(snapshot));if(!discovery&&rows.length&&tab==='research'){sessionStorage.setItem('ad-research-last-success-v1',JSON.stringify(snapshot));setLastResearch(snapshot);}}catch{setStorageMessage('This browser could not keep the current search. Export your research to keep it.');}},[ready,loading,view,coverage,query,submitted,rows,live,at,page,discovery,cursor,sort,tab,platform,funnel,period,minReach,term,group,selected]);
 async function load(value:string,pageId='',after='',coverageOverride=''){
  if(searchTimer.current)clearTimeout(searchTimer.current);editing.current=false;if(!value.trim()&&!pageId)return;
  activeSearch.current?.abort();const controller=new AbortController();activeSearch.current=controller;const requestCoverage=coverageOverride||coverage;if(coverageOverride)setCoverage(requestCoverage);if(!after)setQuery(value);const id=++request.current;setLoading(true);setError('');setErrorCode('');let failureCode='META_UNAVAILABLE';
  if(!after){setDiscovery(!pageId);setRows([]);setCursor(null);setPage(pageId);setLive(false);}if(!after){reset();setSelected(null);setSubmitted(value);setTab('research');setCompare([]);}
  try{sessionStorage.removeItem('ad-research-retry-v1');}catch{}
  try{
   const params=new URLSearchParams({q:value,coverage:requestCoverage});if(!pageId)params.set('discover','1');if(pageId)params.set('page',pageId);if(after)params.set('after',after);
   const res=await fetchResearch(params.toString(),controller.signal);const data=res.data;if(id!==request.current)return;
   if(!res.ok){failureCode=data.code||(res.status===400?'BAD_QUERY':'META_UNAVAILABLE');throw Error(data.error||'Search failed.');}
   setPendingResearch(null);setRows(old=>after?[...old,...data.ads.filter((a:Ad)=>!old.some(b=>b.id===a.id))]:data.ads);setLive(true);setAt(data.capturedAt);setPage(data.pageId||'');setDiscovery(data.discovery);setCursor(data.nextCursor);
   if(data.pageId)setRecent(old=>[{query:value,page:data.pageId,name:data.ads[0]?.pageName||value},...old.filter(r=>r.page!==data.pageId)].slice(0,8));
  }catch(e){if(id===request.current&&!controller.signal.aborted){setError(e instanceof Error?e.message:'Search failed.');setErrorCode(failureCode);const pending={query:value,page:pageId,after,coverage:requestCoverage};if(validRecoveryRequest(pending)){setPendingResearch(pending);if(needsLogin(failureCode))try{sessionStorage.setItem('ad-research-retry-v1',JSON.stringify(pending));}catch{}}}}
  finally{if(id===request.current)setLoading(false);}
 }
 useEffect(()=>{if(!ready||resumed.current||new URLSearchParams(window.location.search).get('resume')!=='1')return;resumed.current=true;window.history.replaceState({},'',window.location.pathname);try{const pending=JSON.parse(sessionStorage.getItem('ad-research-retry-v1')||'null');sessionStorage.removeItem('ad-research-retry-v1');if(validRecoveryRequest(pending))void load(pending.query,pending.page,pending.after,pending.coverage);}catch{}},[ready]);
 const retrySearch=()=>{if(pendingResearch)void load(pendingResearch.query,pendingResearch.page,pendingResearch.after,pendingResearch.coverage);};
 const previousResearch=()=>{if(!lastResearch)return;activeSearch.current?.abort();request.current++;if(searchTimer.current)clearTimeout(searchTimer.current);editing.current=false;setLoading(false);setError('');setErrorCode('');restoreSnapshot(lastResearch);};
 const openBoard=()=>{activeSearch.current?.abort();request.current++;if(searchTimer.current)clearTimeout(searchTimer.current);editing.current=false;setLoading(false);setError('');setErrorCode('');setTab('saved');setView('ads');setDiscovery(false);};
 useEffect(()=>{if(!ready||!editing.current)return;const value=query.trim();if(value.length<2)return;searchTimer.current=setTimeout(()=>void load(value),700);return()=>{if(searchTimer.current)clearTimeout(searchTimer.current);};},[query,ready,coverage]);
 const editQuery=(value:string)=>{try{sessionStorage.removeItem('ad-research-retry-v1');}catch{}request.current++;activeSearch.current?.abort();if(searchTimer.current)clearTimeout(searchTimer.current);editing.current=true;setQuery(value);setSubmitted(value.trim());setDiscovery(true);setRows([]);setCursor(null);setPage('');setError('');setErrorCode('');setPendingResearch(null);setSelected(null);setCompare([]);setTab('research');setLoading(value.trim().length>=2);};
 const sample=()=>{setPendingResearch(null);setErrorCode('');try{sessionStorage.removeItem('ad-research-retry-v1');}catch{}if(searchTimer.current)clearTimeout(searchTimer.current);activeSearch.current?.abort();editing.current=false;setQuery('');setSelected(null);setView('ads');request.current++;setLoading(false);setRows(sampleAds);setLive(false);setAt(capturedSample);setPage('280531915302272');setDiscovery(false);setCursor(null);setSubmitted('Sharps');setError('');setCompare([]);};
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const abort=new AbortController();Promise.resolve(ctx.registerTool({name:'search_brand',title:'Research a brand',description:'Request live UK Meta ads; select a matching advertiser from keyword discovery.',inputSchema:{type:'object',properties:{query:{type:'string',minLength:1,maxLength:200}},required:['query'],additionalProperties:false},execute(input:any){if(typeof input?.query!=='string'||!input.query.trim()||input.query.length>200)throw Error('Enter a brand or URL.');void load(input.query);return {status:'Search requested'};}},{signal:abort.signal})).catch(()=>{});return()=>abort.abort();},[coverage]);
 const source=tab==='saved'?saved:rows;
 const visible=useMemo(()=>{let a=source.filter(a=>(platform==='all'||a.platforms?.includes(platform))&&(funnel==='all'||stage(a)===funnel)&&(period==='all'||(a.start&&elapsed(a,at)<=Number(period)))&&(!minReach||(a.reach!=null&&a.reach>=Number(minReach)))&&(!term||`${a.title} ${a.copy} ${a.pageName||'Sharps'}`.toLowerCase().includes(term.toLowerCase())));a=sortAds(a,sort,at);if(group&&view==='ads'){const seen=new Set();a=a.filter(ad=>{const key=pattern(ad);if(seen.has(key))return false;seen.add(key);return true;});}return a;},[source,platform,funnel,period,minReach,term,sort,at,group,view]);
 const platforms=Array.from(new Set(source.flatMap(a=>a.platforms||[]))).sort();const top=sortAds(source,'reach',at).find(a=>a.reach!=null);const longest=sortAds(source,'longest',at).find(a=>a.start);const offerCount=source.filter(a=>stage(a)==='BOFU').length;const patterns=new Set(source.map(pattern)).size;const name=discovery?'Choose your advertiser':rows[0]?.pageName||(live?submitted:'Sharps Fitted Furniture');
 const recordFormat=useCallback((id:string,format:CreativeFormat)=>{if(format==='Unknown')return;setRows(current=>current.map(a=>a.id===id?{...a,format:a.format==='Mixed'?'Mixed':a.format!=='Unknown'&&a.format!==format?'Mixed':format}:a));},[]);
 const isSaved=(a:Ad)=>saved.some(s=>s.id===a.id);const save=(a:Ad)=>setSaved(old=>old.some(s=>s.id===a.id)?old.filter(s=>s.id!==a.id):[a,...old]);const compareAd=(a:Ad)=>setCompare(old=>old.some(s=>s.id===a.id)?old.filter(s=>s.id!==a.id):old.length<3?[...old,a]:old);
 const reset=()=>{setPlatform('all');setFunnel('all');setPeriod('all');setMinReach('');setTerm('');setGroup(false);};
 const advertisers=Array.from(new Map([...matchingAdvertisers(submitted,recent.map(r=>({pageId:r.page,pageName:r.name,aliases:[r.query]}))),...rows.filter(a=>a.pageId&&/^\d+$/.test(a.pageId)).map(a=>({pageId:a.pageId!,pageName:a.pageName||'Advertiser',aliases:[]}))].map(a=>[a.pageId,a])).values()).sort((a,b)=>advertiserScore(b.pageName,submitted)-advertiserScore(a.pageName,submitted)||a.pageName.localeCompare(b.pageName));
 if(!ready)return <main className="workspace"><p role="status">Restoring your research…</p></main>;
 return <main className="research-product"><header className="app-header"><a className="wordmark" href="/"><span className="logo"><CreativeMark/></span>ad<span className="wordmark-light">library</span><span className="wordmark-caption">CREATIVE LAB</span></a><span className="workspace-name">A little curiosity. A better campaign.</span><div className="header-right"><span className="preview-label">{coverage==='GB'?'UK':'UK + EU'} · Meta Ad Library</span><span className="avatar">RW</span></div></header>
 <section className="workspace"><div className="title-row creative-hero"><div className="hero-copy"><div className="eyebrow"><span className="hero-dot"/>FOR THE NEXT BIG IDEA</div><h1>Good ads.<br/><span>Great ideas.</span><svg className="hero-underline" viewBox="0 0 350 20" aria-hidden="true"><path d="M5 13C96 2 220 3 344 9M9 18C130 11 247 11 325 15" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg></h1><p className="hero-subtitle">Explore what other brands are saying.<br/>Connect the dots for your next campaign.</p><div className="hero-bottom"><span>Explore. Save. Make it your own.</span><button className="outline-button" onClick={()=>download('ad-research.csv',csv(visible,at,notes),'text/csv;charset=utf-8')} disabled={!visible.length||discovery||loading}><Download size={16}/>Export research</button></div></div><CreativeMoodboard/></div>
 <form className="brand-search" onSubmit={e=>{e.preventDefault();void load(query);}}><Search size={22}/><input aria-label="Brand name or website URL" placeholder="Who are we getting curious about? Brand or website…" value={query} onChange={e=>editQuery(e.target.value)} maxLength={200} required/><select aria-label="Ad search coverage" value={coverage} onChange={e=>{setCoverage(e.target.value);editQuery(query);}}><option value="GB">United Kingdom</option><option value="EU_UK">UK + EU</option></select><button className="primary-button" disabled={loading}>{loading?'Searching…':'Research brand'}<ArrowUpRight size={16}/></button></form>
 <p className="search-help">Type a brand or paste a website. Choose a matching advertiser to research · Active {coverage==='GB'?'UK':'UK + EU'} ads.</p><div className="quick-searches"><span>Recent research</span>{recent.map(r=><button key={r.page} onClick={()=>{setQuery(r.query);void load(r.query,r.page);}} disabled={loading}>{r.name}</button>)}<button onClick={sample}>Sharps sample</button></div>
 {error&&<p className="search-error" role="alert">{needsLogin(errorCode)||errorCode==='META_ACCESS_DENIED'?'Live search is unavailable. Please try again shortly.':error} <button className="text-button" disabled={loading} onClick={retrySearch}>Retry search</button></p>}{storageMessage&&<p role="status">{storageMessage}</p>}
 {discovery&&(!error||advertisers.length>0)&&<section className="advertiser-picker"><div className="eyebrow">STEP 1 · CHOOSE A BRAND</div><h2>{loading&&!advertisers.length?'Finding advertisers…':submitted.length<2?'Find your next competitor':`Select a brand for “${submitted}”`}</h2><p>Choose the advertiser you want to research. Live ad availability is checked after selection.</p><div className="advertiser-results">{advertisers.map(a=><button className="advertiser-choice" key={a.pageId} disabled={loading} onClick={()=>load(submitted,a.pageId)} aria-label={`Select ${a.pageName}`}><BrandLogo id={a.pageId} name={a.pageName}/><span className="advertiser-choice-name"><strong>{a.pageName}</strong><small>{rows.some(row=>row.pageId===a.pageId)?'Matched advertiser':'Previously verified advertiser'} · Page {a.pageId}</small></span><span className="advertiser-choice-action">View ads <ArrowUpRight size={16}/></span></button>)}</div>{!advertisers.length&&!loading&&!error&&<p>{submitted.length<2?'Type at least two characters to find advertisers.':`No matching advertisers returned with active ${coverage==='GB'?'UK':'UK + EU'} ads. Try the brand’s trading name or Facebook Page URL.`}</p>}{!loading&&cursor&&<button className="outline-button" onClick={()=>load(submitted,'',cursor)}>Find more advertisers</button>}{!loading&&submitted.trim().length>=2&&<a className="outline-button library-search-link" href={librarySearchUrl(submitted,coverage)} target="_blank" rel="noreferrer">Search “{submitted}” in Ad Library <ExternalLink size={15}/></a>}<details className="advertiser-advanced"><summary>Can't find the right brand?</summary><p>Keyword matches can include unrelated businesses. A website supplies a search term. You can also paste a Facebook Page URL or enter its numeric Page ID. Choose UK + EU to broaden the search. The API does not cover every worldwide commercial ad.</p><form onSubmit={e=>{e.preventDefault();const id=new FormData(e.currentTarget).get('page') as string;void load(submitted,id);}}><input name="page" aria-label="Advertiser Page ID" placeholder="Enter Facebook advertiser Page ID" pattern="[0-9]{1,30}" required/><button className="primary-button" disabled={loading}>Open advertiser</button></form></details></section>}
 {!discovery&&(rows.length>0||tab==='saved')&&<>
  <div className="brand-row"><BrandLogo id={page} name={name}/><div className="brand-identity"><h2>{name}</h2><span className="data-caption">{live?`Retrieved ${new Date(at).toLocaleString('en-GB')}`:'Verified sample · 8 Oct 2026'} · {rows.length} ads loaded {cursor?'· More available':''}</span></div><button className="outline-button refresh-button" disabled={loading} onClick={()=>load(submitted,page)}><RefreshCw size={15}/>Refresh live</button></div>
 {view==='ads'&&<><CreativeMix ads={source} sample={!live}/><section className="research-stats" aria-label="Research overview"><div><span>Ads loaded</span><strong>{source.length}</strong><small>{patterns} distinct copy patterns</small></div><div><span>Highest reported UK reach</span><strong>{number(top?.reach)}</strong><small>One ad · not deduplicated across ads</small></div><div><span>Longest running</span><strong>{longest?elapsed(longest,at)+' days':'Unavailable'}</strong><small>At retrieval · study sustained messages</small></div><div><span>Offer-led messaging</span><strong>{source.length?Math.round(offerCount/source.length*100):0}%</strong><small>Copy-based heuristic · {offerCount} ads</small></div></section>
 <section className="research-insight"><Sparkles size={22}/><div><strong>Your research direction</strong><p>{top?`Start with “${top.title}” (${number(top.reach)} reported UK reach), then compare it with a long-running ad. Look for repeated hooks, proof and offers before choosing one variable to test.`:'Compare repeated messages and long-running ads to identify a testable creative hypothesis.'}</p><small>Reach and longevity are exposure signals. Meta does not provide competitor conversions, ROAS or profitability here.</small></div></section>
 </>}<div className="research-toolbar"><div className="product-tabs" role="tablist" aria-label="Research collections"><button role="tab" aria-selected={tab==='research'&&view==='ads'} onClick={()=>{setTab('research');setView('ads');}}>Discover <span>{rows.length}</span></button><button role="tab" aria-selected={view==='map'} onClick={()=>{setTab('research');setView('map');}}>Messaging map</button><button role="tab" aria-selected={tab==='saved'&&view==='ads'} onClick={()=>{setTab('saved');setView('ads');}}><Bookmark size={15}/>Research board <span>{saved.length}</span></button></div><div className="toolbar-right">{view==='ads'&&<label className="autoplay-toggle"><input type="checkbox" checked={autoplay} onChange={e=>{setAutoplay(e.target.checked);try{localStorage.setItem('ad-autoplay',String(e.target.checked));}catch{}}}/>Autoplay · muted</label>}<button className="outline-button" onClick={()=>setFilters(!filters)} aria-expanded={filters}><SlidersHorizontal size={15}/>Filters</button>{view==='ads'&&<select aria-label="Rank ads" value={sort} onChange={e=>setSort(e.target.value)}><option value="reach">Top ads · UK reach</option><option value="impressions">Impressions · lower bound</option><option value="longest">Longest running</option><option value="newest">Newest launches</option></select>}</div></div>
 {filters&&<section className="product-filters"><label>Platform<select value={platform} onChange={e=>setPlatform(e.target.value)}><option value="all">All platforms</option>{platforms.map(p=><option key={p}>{p}</option>)}</select></label><label>Funnel estimate<select value={funnel} onChange={e=>setFunnel(e.target.value)}><option value="all">All stages</option>{['TOFU','MOFU','BOFU'].map(f=><option key={f}>{f}</option>)}</select></label><label>Started within<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">Any time</option><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option></select></label><label>Minimum UK reach<input aria-label="Minimum UK reach" type="number" min="0" value={minReach} onChange={e=>setMinReach(e.target.value)}/></label><button className="text-button" onClick={reset}>Reset</button></section>}
 <div className="result-row"><p><strong>{visible.length} ads</strong> {tab==='saved'?'on your board':'in loaded results'}{group&&view==='ads'?' · One per copy pattern':''}</p><div className="within-search"><Search size={15}/><input aria-label="Search within ads" placeholder="Search hooks & copy…" value={term} onChange={e=>setTerm(e.target.value)}/></div></div>{view==='ads'&&<div className="ranking-note"><label><input type="checkbox" checked={group} onChange={e=>setGroup(e.target.checked)}/>Group identical copy</label><span>{sort==='reach'?'Ranked by reported UK reach within loaded ads.':sort==='impressions'?'Ranked by the lower bound of available impression ranges; unavailable values appear last.':sort==='longest'?'Ranked by days since first delivery.':'Ranked by first delivery date.'} {cursor&&tab==='research'?'Load all pages before drawing conclusions.':''}</span></div>}
 {view==='ads'&&sort==='impressions'&&!source.some(a=>impressionLower(a)!=null)&&<p className="metric-explainer">Meta returned no impression ranges for these ads. UK reach counts reported accounts reached; impressions count ad appearances. They are different metrics. Try UK reach to rank this set.</p>}
 {view==='map'?<MessagingMap key={page||name} ads={visible} brand={name} pageId={page} at={at} onAd={setSelected}/>:<><div className="creative-grid">{visible.map((a,i)=><article className="ad-card" key={a.id}><div className="card-header"><span className="rank-number">{i+1}</span><strong>{a.pageName||'Sharps Fitted Furniture'}</strong><button className={'save-button '+(isSaved(a)?'saved':'')} aria-label={(isSaved(a)?'Unsave ':'Save ')+a.id} onClick={()=>save(a)}><Bookmark size={18} fill={isSaved(a)?'currentColor':'none'}/></button></div><CreativePreview key={a.id} ad={a} enabled={mediaEnabled} autoplay={autoplay&&!selected&&!comparing} onFormat={recordFormat} onDetails={()=>setSelected(a)}/><div className="card-body"><div className="card-tags"><span className="status">Active at retrieval</span><span className="angle-tag">{a.angle}</span><span className="angle-tag">{stage(a)} · estimated</span></div><h3>{a.title}</h3><div className="primary-metric"><span>UK reach</span><strong>{number(a.reach)}</strong></div><dl><div><dt>Impressions</dt><dd>{impressionLabel(a)}</dd></div><div><dt>Started</dt><dd>{a.start?new Date(a.start+'T12:00:00Z').toLocaleDateString('en-GB'):'Unavailable'}</dd></div><div><dt>Running time</dt><dd>{a.start?elapsed(a,at)+(elapsed(a,at)===1?' day':' days'):'Unavailable'}</dd></div><div><dt>Platforms</dt><dd>{a.platforms?.join(', ')||'Not captured'}</dd></div></dl>{notes[a.id]&&<p className="note-indicator">Research note added</p>}</div><div className="card-footer"><button onClick={()=>setSelected(a)}>Analyse & brief <ArrowUpRight size={14}/></button><button aria-pressed={compare.some(c=>c.id===a.id)} disabled={compare.length>=3&&!compare.some(c=>c.id===a.id)} onClick={()=>compareAd(a)}><GitCompareArrows size={14}/>{compare.some(c=>c.id===a.id)?'Selected':'Compare'}</button></div></article>)}</div>
 {!visible.length&&<section className="empty-state"><Bookmark size={30}/><h3>{tab==='saved'?'Build a board for your next campaign':'No matching ads'}</h3><p>{tab==='saved'?'Save ads worth studying, add notes and export a test brief.':'Try clearing filters or searching a different advertiser.'}</p><button className="outline-button" onClick={()=>{reset();if(tab==='saved')setTab('research');}}>Explore ads</button></section>}
 </>}<div className="load-footer">{tab==='research'&&cursor&&<button className="primary-button" disabled={loading} onClick={()=>load(submitted,page,cursor)}>{loading?'Loading…':'Load more ads'}</button>}<p>{live?'Live Meta data':'Sample data'} · {coverage==='GB'?'UK':'UK + EU'} coverage · Research board and notes saved on this device</p><p>Ranking covers loaded ads only. Identical copy can belong to different creatives.</p></div>
 </>} </section>{compare.length>0&&<div className="compare-dock"><span>{compare.length}/3 ads selected</span><button className="primary-button" disabled={compare.length<2} onClick={()=>setComparing(true)}>Compare side by side</button><button aria-label="Clear comparison" onClick={()=>setCompare([])}><X size={18}/></button></div>}
 <Sheet open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><SheetContent className="detail-panel sm:max-w-[620px] w-full overflow-y-auto"><SheetHeader><div className="eyebrow">FROM REFERENCE TO EXPERIMENT</div><SheetTitle>{selected?.title}</SheetTitle><SheetDescription>{selected?.pageName||'Sharps Fitted Furniture'} · {selected?.id}</SheetDescription></SheetHeader>{selected&&<div className="detail-body"><CreativePreview key={selected.id} ad={selected} enabled={mediaEnabled} autoplay={autoplay} onFormat={recordFormat} onDetails={()=>{}}/><a className="primary-button detail-link" href={metaUrl(selected.id)} target="_blank" rel="noreferrer">View actual creative on Meta <ExternalLink size={16}/></a><h3>Ad copy</h3><p>{selected.copy}</p><dl><div><dt>UK reach</dt><dd>{number(selected.reach)}</dd></div><div><dt>Impressions range</dt><dd>{impressionLabel(selected)}</dd></div><div><dt>Target locations</dt><dd>{selected.locations?.filter(l=>!l.excluded).map(l=>l.name).join(', ')||'Not captured'}</dd></div><div><dt>Excluded locations</dt><dd>{selected.locations?.filter(l=>l.excluded).map(l=>l.name).join(', ')||'Not captured'}</dd></div><div><dt>Target ages</dt><dd>{selected.ages?.join('–')||'Not captured'}</dd></div></dl><div className="analysis-box"><h3><Sparkles size={16}/>Working hypothesis · {stage(selected)}</h3><p>{selected.analysis}</p><p>Compare one hook or offer against your control. Judge the test by qualified leads or purchases, not the competitor’s reach.</p></div><label className="notes-label">Your research notes<textarea aria-label="Research notes" placeholder="What is the hook? What proof makes it credible? What would you test for your brand?" value={notes[selected.id]||''} onChange={e=>setNotes(n=>({...n,[selected.id]:e.target.value}))} maxLength={5000}/></label><div className="detail-actions"><button className="primary-button" onClick={()=>download(`creative-brief-${selected.id}.txt`,brief(selected,notes[selected.id],at))}><Download size={15}/>Export test brief</button><button className="outline-button" onClick={()=>save(selected)}>{isSaved(selected)?<Check size={15}/>:<Bookmark size={15}/>} {isSaved(selected)?'Saved to board':'Save to board'}</button></div><p className="detail-caption">Copy-based hypotheses are estimates. This workspace has no competitor conversion or revenue data. Saved notes remain on this device.</p></div>}</SheetContent></Sheet>
 <Sheet open={comparing} onOpenChange={setComparing}><SheetContent className="detail-panel sm:max-w-[1100px] w-full overflow-y-auto"><SheetHeader><SheetTitle>Which message deserves a test?</SheetTitle><SheetDescription>Compare exposure and messaging. These metrics do not establish sales performance.</SheetDescription></SheetHeader><div className="comparison-grid">{compare.map(a=><div key={a.id}><span className="eyebrow">{a.pageName||'Sharps'}</span><h3>{a.title}</h3><p>{a.copy}</p><dl><div><dt>UK reach</dt><dd>{number(a.reach)}</dd></div><div><dt>Impressions</dt><dd>{impressionLabel(a)}</dd></div><div><dt>Running</dt><dd>{elapsed(a,at)} days</dd></div><div><dt>Funnel estimate</dt><dd>{stage(a)}</dd></div></dl><p>{notes[a.id]||'No research note yet.'}</p><a className="outline-button" href={metaUrl(a.id)} target="_blank" rel="noreferrer">View creative<ExternalLink size={14}/></a></div>)}</div></SheetContent></Sheet><footer className="app-footer"><span>AD Library Scraper</span><a href="https://www.facebook.com/ads/library/api/" target="_blank" rel="noreferrer">Meta data documentation</a><span>Evidence for your next experiment</span></footer></main>;
}
