import {pattern,sortAds,type Ad} from './research';
export type MessageCategory='hooks'|'benefits'|'offers'|'proof'|'actions';
export type MessageTheme={id:string;category:MessageCategory;label:string;ads:Ad[];evidence:Record<string,string>;test:string};
export const messageCategories:{id:MessageCategory;label:string;question:string}[]=[
 {id:'hooks',label:'Hooks',question:'What earns attention?'},{id:'benefits',label:'Benefits',question:'What changes for the customer?'},{id:'offers',label:'Offers',question:'What makes acting attractive?'},{id:'proof',label:'Proof & reassurance',question:'What claims build confidence?'},{id:'actions',label:'Next steps',question:'What does the ad ask people to do?'}];
const rules:{id:string;category:MessageCategory;label:string;match:RegExp;test:string}[]=[
 {id:'tension',category:'hooks',label:'Everyday frustrations',match:/\b(clutter|crammed|dark corners|nothing to wear|struggling|tired of|messy)\b/i,test:'Open with one frustration your customers actually describe. Show how your product addresses it; keep the offer unchanged.'},
 {id:'transformation',category:'hooks',label:'Transformation',match:/\b(transform\w*|makeover|before.?and.?after|refresh|renew|upgrade)\b/i,test:'Test a clear before-and-after story against your current opening. Use an outcome you can demonstrate.'},
 {id:'identity',category:'hooks',label:'Lifestyle & identity',match:/\b(your style|own unique|expression|way you live|things you love|home feels|unwind|relax)\b/i,test:'Test an opening about the customer’s desired way of life, followed by a concrete product benefit.'},
 {id:'discovery',category:'hooks',label:'Discovery & curiosity',match:/\b(discover|explore|introducing|meet|what.?s inside|inside that)\b/i,test:'Give the viewer a specific reason to keep watching. Reveal one useful product detail instead of a vague teaser.'},
 {id:'space',category:'benefits',label:'Space & organisation',match:/\b(storage|maximi[sz]\w*|more space|every inch|organi[sz]\w*|space.saving)\b/i,test:'Demonstrate one practical benefit visually. Compare the benefit-led opening against your existing creative.'},
 {id:'personal',category:'benefits',label:'Made for you',match:/\b(bespoke|tailored|fitted|personali[sz]\w*|designed around)\b/i,test:'Show how your solution adapts to a specific customer need. Keep the audience, offer and landing page consistent.'},
 {id:'choice',category:'benefits',label:'Style & choice',match:/\b(colou?rs?|styles?|finishes|collection)\b/i,test:'Help the customer picture one relevant option. Test a focused example against a broad product showcase.'},
 {id:'ease',category:'benefits',label:'Ease & comfort',match:/\b(easy|easier|effortless|smooth|comfort\w*|seamless\w*)\b/i,test:'Show a moment that becomes easier with your product. Measure qualified responses rather than attention alone.'},
 {id:'saving',category:'offers',label:'Price incentive',match:/\b(sale|half.price|discount|\d+\s*%\s*off|save\s*£|price match|match any)\b/i,test:'If you have a genuine offer, test clearer presentation of its value. Keep the actual offer and eligibility consistent.'},
 {id:'free',category:'offers',label:'Free first step',match:/\bfree\b/i,test:'Test a low-commitment first step that you actually provide. Compare lead quality as well as response volume.'},
 {id:'finance',category:'offers',label:'Payment flexibility',match:/\b(finance|deposit|pay monthly|interest.free)\b/i,test:'If payment options apply, test explaining them clearly with the relevant terms. Do not invent a financial offer.'},
 {id:'endorsement',category:'proof',label:'Ratings & endorsement',match:/\b(which|recommended|award\w*|accredited|rated|reviews?|stars?)\b/i,test:'Place your own substantiated endorsement beside the main benefit. Compare against the same ad without that proof.'},
 {id:'guarantee',category:'proof',label:'Guarantee & longevity',match:/\b(guarantee|warranty|\d+[- ]?year|years? of|since\s+\d{4}|craftsmanship|established)\b/i,test:'Address one buying objection with evidence you can substantiate. Test the placement of reassurance, not a borrowed competitor claim.'},
 {id:'trust',category:'proof',label:'Popularity & trust',match:/\b(trusted|no\.?\s*1|number one|customers?|homeowners|bestsell\w*|leading)\b/i,test:'Use your own customer evidence to support a specific benefit. Judge the test by qualified leads or purchases.'},
 {id:'book',category:'actions',label:'Book a visit',match:/\b(book|design visit|appointment)\b/i,test:'Make the next step and what happens afterwards explicit. Compare the CTA wording while holding the rest of the ad constant.'},
 {id:'brochure',category:'actions',label:'Download a brochure',match:/\b(download|brochure)\b/i,test:'Explain what the download helps someone decide. Track downstream lead quality, not just downloads.'},
 {id:'shop',category:'actions',label:'Shop or order',match:/\b(shop|buy|order)\b/i,test:'Test a direct purchase next step against your current CTA. Keep the destination and offer identical.'},
 {id:'learn',category:'actions',label:'Explore or learn',match:/\b(learn more|find out|discover|explore)\b/i,test:'Tell people exactly what they will find next. Compare a specific CTA against a generic learn-more prompt.'}
];
export function messagingThemes(ads:Ad[]):MessageTheme[]{
 return rules.map(rule=>{const evidence:Record<string,string>={};const matched=ads.filter(ad=>{
 const copy=ad.copy==='No ad copy provided by Meta.'?'':ad.copy;const title=ad.title==='Ad creative'?'':ad.title;const sentences=(copy+'\n'+title).split(/(?<=[.!?])\s+|\n+/).map(s=>s.trim()).filter(Boolean);const sentence=sentences.find(s=>rule.match.test(s));if(sentence)evidence[ad.id]=sentence;return !!sentence;
 });return {id:rule.id,category:rule.category,label:rule.label,ads:matched,evidence,test:rule.test};}).filter(t=>t.ads.length).sort((a,b)=>b.ads.length-a.ads.length||a.label.localeCompare(b.label));
}
export function themeExamples(theme:MessageTheme,at:string){const seen=new Set<string>();return sortAds(theme.ads,'reach',at).filter(ad=>{const key=pattern(ad);if(seen.has(key))return false;seen.add(key);return true;});}
export function messagingExport(brand:string,themes:MessageTheme[],at:string,notes:Record<string,string>){return `MESSAGING MAP — ${brand}\nAd data retrieved: ${at}\nThemes detected from loaded ad text. Claims are not verified; themes overlap. No video/image analysis or competitor conversion data.\n\n`+messageCategories.map(category=>category.label+'\n'+themes.filter(t=>t.category===category.id).map(t=>`• ${t.label} — ${t.ads.length} ads, ${themeExamples(t,at).length} distinct copy patterns\n  Test direction: ${notes[t.id]||t.test}\n`+themeExamples(t,at).map(a=>`  Evidence (${a.id}): ${t.evidence[a.id]}\n  https://www.facebook.com/ads/library/?id=${a.id}`).join('\n')).join('\n\n')).join('\n\n');}
