export type Ad={id:string;title:string;copy:string;start:string;format:string;duration?:string;angle:string;image:string;source:string;analysis:string;pageId?:string;pageName?:string;stop?:string|null;platforms?:string[];reach?:number|null;locations?:{name:string;excluded:boolean}[];ages?:string[];funnel?:string;impressions?:{lower_bound?:string;upper_bound?:string}|null};
export const metaUrl=(id:string)=>`https://www.facebook.com/ads/library/?id=${encodeURIComponent(id)}`;
export const elapsed=(ad:Ad,at:string)=>ad.start?Math.max(1,Math.floor((Date.parse((ad.stop||at.slice(0,10))+'T12:00:00Z')-Date.parse(ad.start+'T12:00:00Z'))/86400000)):0;
export const number=(n:number|null|undefined)=>n==null?'Unavailable':n.toLocaleString('en-GB');
export const impressionLower=(a:Ad)=>a.impressions?.lower_bound!=null&&Number.isFinite(Number(a.impressions.lower_bound))?Number(a.impressions.lower_bound):null;
export function impressionLabel(a:Ad){const i=a.impressions;if(!i)return 'Unavailable';return i.lower_bound!=null&&i.upper_bound!=null?`${number(Number(i.lower_bound))}–${number(Number(i.upper_bound))}`:i.lower_bound!=null?`${number(Number(i.lower_bound))}+`:i.upper_bound!=null?`Up to ${number(Number(i.upper_bound))}`:'Unavailable';}
export const stage=(a:Ad)=>a.funnel||(a.angle==='Offer'?'BOFU':a.angle==='Product'?'MOFU':'TOFU');
export const pattern=(a:Ad)=>`${a.pageId||a.pageName||'sample'}:${a.copy.toLowerCase().replace(/\s+/g,' ').trim()}`;
export function sortAds(ads:Ad[],sort:string,at:string){return [...ads].sort((a,b)=>{if(sort==='reach'||sort==='impressions'){const x=sort==='reach'?a.reach:impressionLower(a),y=sort==='reach'?b.reach:impressionLower(b);if(x==null&&y!=null)return 1;if(y==null&&x!=null)return -1;return (y??-1)-(x??-1)||b.start.localeCompare(a.start)||a.id.localeCompare(b.id);}if(sort==='longest')return elapsed(b,at)-elapsed(a,at)||a.id.localeCompare(b.id);return b.start.localeCompare(a.start)||a.id.localeCompare(b.id);});}
export function csv(ads:Ad[],at:string,notes:Record<string,string>){const cell=(v:unknown)=>'"'+String(v??'').replace(/^[\s]*[=+@-]/,"'$&").replace(/"/g,'""')+'"';return [['Ad ID','Advertiser','Copy','Start date','Days at retrieval','UK reach','Impressions range','Platforms','Funnel estimate','Research note','Meta URL'],...ads.map(a=>[a.id,a.pageName||'Sharps',a.copy,a.start,elapsed(a,at),a.reach,impressionLabel(a),a.platforms?.join(', '),stage(a),notes[a.id],metaUrl(a.id)])].map(row=>row.map(cell).join(',')).join('\r\n');}
export function brief(a:Ad,note:string,at:string){return `CREATIVE TEST BRIEF\nReference: ${a.pageName||'Sharps Fitted Furniture'} — ${a.id}\n${metaUrl(a.id)}\nRetrieved: ${at}\n\nObserved message\n${a.copy}\n\nResearch signals\nUK reach: ${number(a.reach)}; impressions: ${impressionLabel(a)}; running: ${elapsed(a,at)} days. These do not establish conversions or profitability.\n\nWorking hypothesis\n${a.angle==='Offer'?'A clear offer and low-friction next step may increase qualified responses.':a.angle==='Product'?'A specific product benefit may help consideration.':'An audience-relevant story may improve attention.'}\n\nYour interpretation\n${note||'Add the audience tension, hook and objection you want to test.'}\n\nTest plan\nCreate an original creative for your brand using this messaging principle. Compare one changed hook against your control with the same audience, offer and landing page.\n\nMeasure\nPrimary: cost per qualified lead or purchase. Supporting: click-through rate, landing-page conversion and lead quality. Set budget and stopping rules before launch.\n\nCreative direction\nHook: [your opening line]\nProof: [your substantiated evidence]\nOffer: [your offer]\nCTA: [your next step]\n\nFunnel estimate: ${stage(a)} (copy-based heuristic, not Meta targeting or performance).`;
}
