import type {Ad} from "./research";
const images=["https://cdn.sharps.co.uk/media/assets/studio-collection-phase-two/studio-duskypink-sorrento-560x700.jpg","https://cdn.sharps.co.uk/media/assets/homepage/banner/which_room_living-25.jpg","https://cdn.sharps.co.uk/media/assets/homepage/banner/which_room_office.jpg"];
const sale="Half Price Sale Now On. Plus an extra 20% off. Transform your space with the UK's No.1 fitted furniture company, backed by an industry-leading 15-year guarantee. Book your free design visit with Sharps today.";
export const sampleAds:Ad[]=[
{id:"1439262321695837",platforms:["facebook","instagram","messenger","threads"],reach:47,ages:["25","65"],funnel:"TOFU",title:"It's what's inside that counts",copy:"Explore fitted furniture that's designed around you, and the things you love.",start:"2026-10-07",format:"Video",duration:"0:06",angle:"Lifestyle",image:images[0],source:"Meta API",analysis:"The headline shifts attention from furniture to the things a customer values. A lifestyle-led awareness angle. This is an editorial interpretation of the copy, not a Meta performance metric."},
{id:"1675773394116893",title:"Fitted furniture for every room",copy:"Open this ad in Meta to inspect its creative variants. Body text was not exposed in the captured preview.",start:"2026-09-30",format:"Video",duration:"1:00",angle:"Brand",image:images[1],source:"Meta Ad Library",analysis:"The longer video format can accommodate a broader brand story. Its hook and visual sequence still need review; duration alone does not tell us how well it performs."},
{id:"1371182101209589",title:"Book your free design visit today",copy:"Half Price Sale Now On. Plus an extra 20% off. Transform your space with the UK's No.1 fitted furniture company and Which? Recommended Provider for Fitted Bedrooms. Book your free design visit with Sharps today.",start:"2026-08-21",format:"Image",angle:"Offer",image:images[2],source:"Meta Ad Library",analysis:"The offer stacks two price incentives and uses independent endorsement as reassurance. A free design visit lowers the next-step commitment. An offer-led conversion angle; actual conversion results are unavailable."},
{id:"2628255447612072",title:"One home. Endless possibilities",copy:"Explore our Studio Collection and showcase your own unique expression with a curated selection of colours, styles and frames.",start:"2026-08-12",format:"Image",angle:"Product",image:images[0],source:"Meta Ad Library",analysis:"Personal expression and variety are the core benefits. A product-led consideration angle, with a specific collection for interested customers to explore."},
{id:"1744405716612975",title:"Book your free design visit today",copy:sale,start:"2026-08-21",format:"Video",duration:"0:10",angle:"Offer",image:images[1],source:"Meta Ad Library",analysis:"This short video pairs a sale with a long guarantee. The guarantee addresses durability concerns, while a free appointment reduces friction. These are messaging observations, not measured outcomes."},
{id:"1117562100730661",title:"Built to last, designed to renew",copy:"Keep what matters and refresh what you see with Sharps Renew for Sharps Signature wardrobes. Perfect storage with style that changes with you.",start:"2026-09-24",format:"Video",duration:"0:39",angle:"Product",image:images[2],source:"Meta Ad Library",analysis:"The copy reframes furniture as adaptable over time. It pairs longevity with changing style, giving this creative a distinct angle from the price-led sale ads."}];
